SELECT MISSION_OUTCOME FROM SPACEXTBL;

--1.
SELECT COUNT (DISTINCT LAUNCH_SITE) 
FROM SPACEXTBL;

--2.
SELECT LAUNCH_SITE 
FROM SPACEXTBL 
WHERE LAUNCH_SITE LIKE 'KSC%';

--3.
SELECT SUM(PAYLOAD_MASS__KG_)
FROM SPACEXTBL
WHERE CUSTOMER LIKE 'NASA%';

--4
SELECT AVG(PAYLOAD_MASS__KG_)
FROM SPACEXTBL
WHERE  BOOSTER_VERSION LIKE 'F9 v1.1%';

--5
SELECT MIN(DATE)
FROM SPACEXTBL
WHERE MISSION_OUTCOME = 'Success';

--6
SELECT BOOSTER_VERSION
FROM SPACEXTBL
WHERE PAYLOAD_MASS__KG_ BETWEEN 4000 and 6000;

--7
SELECT COUNT (MISSION_OUTCOME) as TOTAL_SUCCESSFUL_MISSIONS
FROM SPACEXTBL
WHERE MISSION_OUTCOME = 'Success';

SELECT COUNT (MISSION_OUTCOME) as TOTAL_FAILED_MISSIONS
FROM SPACEXTBL
WHERE MISSION_OUTCOME LIKE 'Failure%';

--8
SELECT BOOSTER_VERSION
FROM SPACEXTBL
WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTBL);

--9
SELECT COUNT(MISSION_OUTCOME) as SUCCESSFUL_LANDING_OUTCOMES
FROM SPACEXTBL
WHERE MISSION_OUTCOME LIKE 'Success%'
AND DATE BETWEEN '2010-06-04' AND '2017-03-20'
GROUP BY YEAR(DATE)
ORDER BY COUNT(MISSION_OUTCOME) DESC;

